// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tag } from "./Tag";

export type BookmarkInterface = {
  identifier: string;
  title: string;
  url: string;
  tag: Tag;
  createdAt: string;
  updatedAt: string;
  workspaceIdentifier: string | null;
};
