// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateNote = {
  title: string;
  content: string;
  categories: Array<string> | null;
  workspaceIdentifier: string | null;
};

export type UpdateNote = {
  title: string | null;
  content: string | null;
  categories: Array<string> | null;
};
