// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationType =
  | "backup_failed"
  | "backup_success"
  | "workspace_invite_received"
  | "workspace_invite_accepted"
  | "workspace_invite_declined"
  | "item_shared"
  | "item_unshared"
  | "item_updated"
  | "item_deleted"
  | "item_access_granted"
  | "item_access_revoked"
  | "generic";
