// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationType } from "./NotificationType";

export type CreateNotification = {
  title: string;
  body: string;
  notificationType: NotificationType;
  workspaceIdentifier: string | null;
  isRead: boolean;
};
