// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemType } from "./ItemType";

export type CreateRecycleBinEntry = {
  itemId: string;
  itemType: ItemType;
  payload: string;
  workspaceIdentifier: string | null;
};
