// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemType } from "./ItemType";

export type RecycleBinInterface = {
  identifier: string;
  itemId: string;
  itemType: ItemType;
  payload: string;
  deletedAt: string;
  workspaceIdentifier: string | null;
};
