// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateReminder = {
  title: string;
  description: string | null;
  recurring: boolean;
  recurrenceRule: string | null;
  alarmSound: string | null;
  remindAt: string;
  workspaceIdentifier: string | null;
};

export type UpdateReminder = {
  title: string | null;
  description: string | null;
  recurring: boolean | null;
  recurrenceRule: string | null;
  alarmSound: string | null;
  remindAt: string | null;
};
