// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateSnippet = {
  title: string | null;
  language: string | null;
  code: string;
  description: string | null;
  isPinned: boolean;
  createdAt: string;
  updatedAt: string;
  workspaceIdentifier: string | null;
};

export type Snippet = {
  title: string | null;
  language: string | null;
  code: string;
  description: string | null;
  isPinned: boolean;
  createdAt: string;
  updatedAt: string;
};

export type UpdateSnippet = {
  title: string | null;
  language: string | null;
  code: string | null;
  description: string | null;
  isPinned: boolean | null;
};
