// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncQueueInterface = {
  identifier: string;
  tableName: string;
  recordIdentifier: string;
  operation: string;
  createdAt: string;
};
