// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from "./Priority";

export type CreateTodo = {
  title: string;
  description: string | null;
  dueDate: string | null;
  priority: Priority;
};

export type UpdateTodo = { title: string | null; description: string | null };
