// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateUserPreferences = {
  masterFirstName: string;
  masterLastName: string;
  masterEmail: string;
};

export type UpdateUserPreferences = {
  masterFirstName: string | null;
  masterLastName: string | null;
  masterEmail: string | null;
};
