// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateWorkspace = { name: string; description: string };

export type UpdateWorkspace = {
  name: string | null;
  description: string | null;
  isDefault: boolean | null;
  isHidden: boolean | null;
  isSecured: boolean | null;
  /**
   * Plain-text password to be hashed; set to Some("") to remove the password.
   */
  password: string | null;
};
